<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>namaste3-sniff</AssemblyName>
    <RootNamespace>Namaste3.Codec.Sniff</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Namaste3.Codec/Namaste3.Codec.csproj" />
  </ItemGroup>

</Project>
